export enum SimulationState {
  IDLE = 'IDLE',
  ATTACK_INITIATED = 'ATTACK_INITIATED',
  EMAIL_OPENED = 'EMAIL_OPENED',
  AGENT_PROCESSING = 'AGENT_PROCESSING',
  SHIELD_INTERVENTION = 'SHIELD_INTERVENTION',
  RESOLVED = 'RESOLVED'
}
